name: hidroly
description: "Track your water intake."
publish_to: 'none'
version: 1.3.2+8

environment:
  sdk: ^3.8.1

dependencies:
  app_settings: ^6.1.1
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.2
  haptic_feedback: ^0.5.1+1
  intl: any
  logger: ^2.6.2
  mocktail: ^1.0.4
  path: ^1.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.2
  workmanager: ^0.9.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
